services:
  db:
    image: postgres:15
    container_name: torneos_db
    environment:
      POSTGRES_DB: torneos
      POSTGRES_USER: torneos_user
      POSTGRES_PASSWORD: torneos_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/Torneos.Api
    container_name: torneos_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8000
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=torneos;Username=torneos_user;Password=torneos_pass
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    volumes:
      - ./backend/Torneos.Api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: torneos_front
    environment:
      VITE_API_URL: http://localhost:8000
      CHOKIDAR_USEPOLLING: "true"  # ayuda a hot reload en docker/win
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
